###

POST http://localhost:3000/campaigns
Content-Type: application/json

{
    "name": "Teclado ABC",
    "content": "Algum conteudo qualquer!",
    "emails": ["evandersondev@mail.com", "asafedias@mail.com"]
}

###

GET http://localhost:3000/campaigns
